# Generated by Django 5.1 on 2024-08-09 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('battle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pokemon_a', models.CharField(max_length=100)),
                ('pokemon_b', models.CharField(max_length=100)),
                ('status', models.CharField(default='BATTLE_INPROGRESS', max_length=50)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
